nome = input("Digite seu nome completo: ").strip()
print("analisando seu nome...")
mai = nome.upper()
print(f"Seu nome em maiusculo é {mai}")
menor = nome.lower()
print(f"Seu nome em minusculo é {menor}")
print(f"Seu nome tem ao todo {len(nome) - nome.count(' ')} letras")
separar = nome.split()
#print(f"Seu primeiro nome é {separar[0]} e tem {nome.find(' ')} letras")
print(f"Seu primeiro nome é {separar[0]} e tem {len(separar[0])} letras")
